# Use official Node.js image as base
FROM node:20-alpine

# Create app directory
WORKDIR /usr/src/app

# Install dependencies
COPY package.json yarn.lock ./
RUN yarn install

# Copy source
COPY . .

# Expose dev port
EXPOSE 3000

# Start in development mode
CMD ["yarn", "dev"]
