import ZennArticleItem from "@/app/blog/_containers/zenn-article-item"
import ZennAsideArticleItem from "@/app/blog/_containers/zenn-aside-article-item"
import { Breadcrumb, LowerTitle } from "@/components/ui"
import { LowerSubTitle } from "@/components/ui/lower-sub-title"
import type { ZennProps } from "@/types"
import { logger } from "@/utils/logger"
import { PATH } from "@/utils/path"
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "To You Design - Blog",
  description: "Generated by Next.js",
}

const Blog = async () => {
  let zennArticles: ZennProps | null = null

  // zennの記事をfetch
  try {
    logger.info("Fetching Zenn articles")
    const response = await fetch("https://zenn.dev/api/articles?username=643866", {
      next: { revalidate: 60 * 60 * 24 * 30 }, // 30日間キャッシュ
    })
    zennArticles = await response.json()
    logger.info(
      {
        length: zennArticles?.articles.length,
        data: zennArticles?.articles[0],
      },
      "https://zenn.dev/api/articles?username=643866",
    )
  } catch (err) {
    logger.error(err, "Failed to fetch Zenn articles")
  }
  //zennの記事を新しい順にsort
  zennArticles?.articles.sort((a, b) => {
    return new Date(b.published_at).getTime() - new Date(a.published_at).getTime()
  })

  return (
    <main>
      <div className="max_width">
        <Breadcrumb items={[{ name: "Blog", link: PATH.BLOG }]} />
      </div>
      <LowerTitle title="Blog" enTitle="ブログ" />
      <div className="blog__layout max_width">
        <div>
          <LowerSubTitle title="Zenn" count={zennArticles?.articles.length ?? 0} />

          <div className="blog__List">
            {zennArticles?.articles.map((article) => (
              <ZennArticleItem
                key={article.id}
                zenn_id={article.id}
                zenn_title={article.title}
                zenn_published_at={article.published_at}
                zenn_article_type={article.article_type}
                zenn_emoji={article.emoji}
                zenn_path={article.path}
              />
            ))}
          </div>
        </div>
        <div className="blog__aside">
          <h2>おすすめ記事</h2>
          <div className="blog__aside__List">
            {zennArticles?.articles.slice(0, 4).map((article) => (
              <ZennAsideArticleItem
                key={article.id}
                zenn_id={article.id}
                zenn_title={article.title}
                zenn_published_at={article.published_at}
                zenn_article_type={article.article_type}
                zenn_emoji={article.emoji}
                zenn_path={article.path}
              />
            ))}
          </div>
        </div>
      </div>
    </main>
  )
}

export default Blog
