import type { Metadata } from "next"
import { PATH } from "../../utils/path"
import { Breadcrumb, LowerTitle } from "../components/ui/"
import { CareerHistoryTimeline, JobTimeline, LicenseList } from "../components/ui/rsc"
import { AboutTabs } from "./_containers/about-tabs"

export const metadata: Metadata = {
  title: "To You Design - About",
  description: "Generated by Next.js",
}

const About = () => {
  return (
    <main className="u-padding">
      <div className="max_width">
        <Breadcrumb items={[{ name: "About", link: PATH.ABOUT }]} />
      </div>
      <LowerTitle title="About" enTitle="プロフィール" />
      {/* @ts-expect-error 非同期サーバーコンポーネントはPromiseを返すため型エラーになりますが、Next.jsが実行時に解決します https://zenn.dev/duo3/articles/7be016e771c3e4 */}
      <AboutTabs historyContent={<JobTimeline />} careerContent={<CareerHistoryTimeline />} />

      {/* ここからLicense*/}
      <section className="license max_width">
        <h3 className="lower__subTitle">資格</h3>
        <table className="license__table">
          <tbody>
            <tr>
              <th className="license__table-th">日付</th>
              <th className="license__table-th">資格名</th>
            </tr>
            {/* @ts-expect-error 非同期サーバーコンポーネントはPromiseを返すため型エラーになりますが、Next.jsが実行時に解決します https://zenn.dev/duo3/articles/7be016e771c3e4 */}
            <LicenseList />
          </tbody>
        </table>
      </section>
    </main>
  )
}

export default About
