import React from "react";
import { PATH } from "../../utils/path";
import BreadList from "../components/ui/BreadList";
import { Timelines } from "../components/ui/rsc/Timelines";
import { HistoryTimelines } from "../components/ui/rsc/HistoryTimelines";
import { License } from "../components/ui/rsc/License";
import { LowerTitle } from "../components/ui/LowerTitle";

export const metadata = {
	title: "To You Design - About",
	description: "Generated by Next.js",
};

const About = () => {
	return (
		<main className="padding">
			<div className="max_width">
				<BreadList name="About" link={PATH.ABOUT} />
			</div>
			<LowerTitle title="About" enTitle="プロフィール" />
			<div className="max_width">
				<h3 className="portfolio__headTitle">経歴</h3>
				<HistoryTimelines />
			</div>

			{/*ここから職歴*/}
			<div className="max_width">
				<h3 className="portfolio__headTitle">職歴</h3>
				<Timelines />
			</div>

			{/* ここからLicense*/}
			<section className="license max_width">
				<h3 className="portfolio__headTitle">資格</h3>
				<table className="license__table">
					<tbody>
						<tr>
							<th className="license__table__th">日付</th>
							<th className="license__table__th">資格名</th>
						</tr>
						<License />
					</tbody>
				</table>
			</section>
		</main>
	);
};

export default About;
