import type { Metadata } from "next"
import { PATH } from "../../utils/path"
import { Breadcrumb, LowerTitle } from "../components/ui"
import { PortfolioList } from "./_containers/portfolio-list"

export const metadata: Metadata = {
  title: "To You Design - Portfolio",
  description: "Generated by Next.js",
}

const Portfolio = () => {
  return (
    <main>
      <div className="max_width">
        <Breadcrumb items={[{ name: "Portfolio", link: PATH.PORTFOLIO }]} />
      </div>
      <LowerTitle title="Portfolio" enTitle="制作物" />
      <PortfolioList />
    </main>
  )
}

export default Portfolio
