import {
  faHtml5,
  faCss3,
  faReact,
  faVuejs,
  faUnity,
  faJs,
  faWordpress,
} from "@fortawesome/free-brands-svg-icons";
import { faGem } from "@fortawesome/free-regular-svg-icons";
import { faCamera } from "@fortawesome/free-solid-svg-icons";

export const portfolios = [
  {
    name: "Nuxttodoサイト",
    date: "2022.1.12",
    tag: "Vue",
    img: "/images/portfolio_8.png",
    url: "https://nuxt-app-front.web.app/",
    color: "portfoli__tag--color3",
    about: "vueについて学びたく、Todoサイトを作りました",
    skill: "Nuxt.js, firebase hosting, firestore",
    time: "1週間",
  },
  {
    name: "ピアサポータル",
    date: "2022.01.01",
    tag: "React",
    img: "/images/portfolio_6.png",
    url: "https://attandance-peer.vercel.app/",
    color: "portfoli__tag--color5",
    about: "サークルの出席管理ができるアプリです。",
    skill: "React, Next.js, firestore",
    time: "2週間",
  },
  {
    name: "サークル管理App",
    date: "2022.11.30",
    tag: "React",
    img: "/images/portfolio_7.png",
    url: "https://rails-react-app-front.vercel.app/",
    color: "portfoli__tag--color5",
    about: "サークルのメンバー管理ができるアプリです。",
    skill: "フロントエンド React バックエンド Ruby on Rails",
    time: "1ヶ月",
  },
  {
    name: "Manga Study",
    date: "2021.10.31",
    tag: "React",
    img: "/images/portfolio_5.png",
    url: "https://todo-app-react-30d63.firebaseapp.com/",
    color: "portfoli__tag--color5",
    about: "漫画の考察記事を投稿できるサイトです",
    skill: "React, Next.js, firestore",
    time: "2ヶ月",
  },
  {
    name: "Todoサイト",
    date: "2021.12.31",
    tag: "React",
    img: "/images/portfolio_4.png",
    url: "https://todo-app-react-30d63.firebaseapp.com/",
    color: "portfoli__tag--color5",
    about: "Todoサイトです。",
    skill: "React",
    time: "1ヶ月",
  },
  {
    name: "三菱レンタカー下層ページ　コーディング",
    date: "2021.09.01",
    tag: "html",
    img: "/images/portfolio_1.png",
    url: "https://www.mmc-dia-finance.com/rental/",
    color: "portfoli__tag--color1",
    about: "案件として、三菱レンタカー下層ページを3-4ページ実装しました。",
    skill: "html,css",
    time: "1ヶ月",
  },
  // {
  //   portfolio_name: "Lutena デザイン＋コーディング",
  //   portfolio_date: "2021.09.01",
  //   portfolio_tag: "Wordpress",
  //   portfolio_img: "/images/portfolio_3.png",
  //   portfolio_url: "https://lutena.net/",
  //   portfolio_color: "portfoli__tag--color2",
  // },
  // {
  //   portfolio_name: "Railsチュートリアル",
  //   portfolio_date: "2021.11.31",
  //   portfolio_tag: "Ruby on Rails",
  //   portfolio_img: "/images/portfolio_2.png",
  //   portfolio_url: "https://sleepy-plains-55156.herokuapp.com/",
  //   portfolio_color: "portfoli__tag--color3",
  // },
];

export const skills = [
  {
    skill_name: "HTML",
    skill_rank: "★★★★",
    skill_tag: "経験年数：3年",
    skill_icon: faHtml5,
  },
  {
    skill_name: "CSS(SCSS)",
    skill_rank: "★★★★",
    skill_tag: "経験年数：3年",
    skill_icon: faCss3,
  },
  {
    skill_name: "JavaScript,TypeScript(jQuery)",
    skill_rank: "★★★",
    skill_tag: "経験年数：2年",
    skill_icon: faJs,
  },
  {
    skill_name: "Ruby on Rails",
    skill_rank: "★★",
    skill_tag: "経験年数：1年",
    skill_icon: faGem,
  },
  {
    skill_name: "React/Next.js",
    skill_rank: "★★★",
    skill_tag: "経験年数：1年",
    skill_icon: faReact,
  },
  {
    skill_name: "Vue.js/Nuxt.js",
    skill_rank: "★",
    skill_tag: "経験年数：1ヶ月",
    skill_icon: faVuejs,
  },
  {
    skill_name: "Unity",
    skill_rank: "★★",
    skill_tag: "経験年数：3ヶ月",
    skill_icon: faUnity,
  },
  // {
  //   skill_name: "Golang",
  //   skill_rank: "★★",
  //   skill_tag: "経験年数：3ヶ月",
  //   skill_icon: faGolang,
  // },
  {
    skill_name: "WordPress",
    skill_rank: "★★★",
    skill_tag: "経験年数：1年",
    skill_icon: faWordpress,
  },
  {
    skill_name: "PhotoShop/Illustrator",
    skill_rank: "★★★",
    skill_tag: "経験年数：1年半",
    skill_icon: faCamera,
  },
];
