import {
  faHtml5,
  faCss3,
  faReact,
  faVuejs,
  faUnity,
  faJs,
  faWordpress,
} from "@fortawesome/free-brands-svg-icons";
import { faGem } from "@fortawesome/free-regular-svg-icons";
import { faCamera } from "@fortawesome/free-solid-svg-icons";

export const portfolios = [
  {
    name: "Nuxttodoサイト",
    date: "2022.1.12",
    tag: "Vue",
    img: "/images/portfolio_8.png",
    url: "https://vuejs-app-front.web.app/",
    github: "https://github.com/takoyan33/nuxt3-firestore-front",
    color: "portfoli__tag--color3",
    about: "vueについて学びたく、Todoサイトを作りました",
    skill: "Nuxt.js, firebase hosting, firestore",
    time: "2週間",
  },
  {
    name: "ピアサポータル",
    date: "2022.01.01",
    tag: "React",
    img: "/images/portfolio_6.png",
    url: "https://attandance-peer.vercel.app/",
    github: "https://github.com/takoyan33/attandance_peer",
    color: "portfoli__tag--color5",
    about: "サークルの出席管理ができるアプリです。",
    skill: "React, Next.js, firestore",
    time: "2週間",
  },
  {
    name: "サークル管理App",
    date: "2022.11.30",
    tag: "React",
    img: "/images/portfolio_7.png",
    url: "https://rails-react-app-front.vercel.app/",
    github: "https://github.com/takoyan33/rails-react-app-front",
    color: "portfoli__tag--color5",
    about: "サークルのメンバー管理ができるアプリです。",
    skill: "フロントエンド React バックエンド Ruby on Rails",
    time: "1ヶ月",
  },
  {
    name: "Manga Study",
    date: "2021.10.31",
    tag: "React",
    img: "/images/portfolio_5.png",
    url: "https://todo-app-react-30d63.firebaseapp.com/",
    github: "https://github.com/takoyan33/manga-kousatu.net",
    color: "portfoli__tag--color5",
    about: "漫画の考察記事を投稿できるサイトです",
    skill: "React, Next.js, firestore",
    time: "2ヶ月",
  },
  {
    name: "Todoサイト",
    date: "2021.12.31",
    tag: "React",
    img: "/images/portfolio_4.png",
    url: "https://todo-app-react-30d63.firebaseapp.com/",
    github: "",
    color: "portfoli__tag--color5",
    about: "Todoサイトです。",
    skill: "React",
    time: "1ヶ月",
  },
  {
    name: "三菱レンタカー下層ページ　コーディング",
    date: "2021.09.01",
    tag: "html",
    img: "/images/portfolio_1.png",
    url: "https://www.mmc-dia-finance.com/rental/",
    github: "",
    color: "portfoli__tag--color1",
    about: "案件として、三菱レンタカー下層ページを3-4ページ実装しました。",
    skill: "html,css",
    time: "1ヶ月",
  },
  // {
  //   portfolio_name: "Lutena デザイン＋コーディング",
  //   portfolio_date: "2021.09.01",
  //   portfolio_tag: "Wordpress",
  //   portfolio_img: "/images/portfolio_3.png",
  //   portfolio_url: "https://lutena.net/",
  //   portfolio_color: "portfoli__tag--color2",
  // },
  // {
  //   portfolio_name: "Railsチュートリアル",
  //   portfolio_date: "2021.11.31",
  //   portfolio_tag: "Ruby on Rails",
  //   portfolio_img: "/images/portfolio_2.png",
  //   portfolio_url: "https://sleepy-plains-55156.herokuapp.com/",
  //   portfolio_color: "portfoli__tag--color3",
  // },
  // {
  //   portfolio_name: "Python",
  //   portfolio_date: "2021.11.31",
  //   portfolio_tag: "Ruby on Rails",
  //   portfolio_img: "/images/portfolio_2.png",
  //   portfolio_url: "https://sleepy-plains-55156.herokuapp.com/",
  //   portfolio_color: "portfoli__tag--color3",
  // },
  // {
  //   portfolio_name: "ハッカソン",
  //   portfolio_date: "2022.11.31",
  //   portfolio_tag: "React",
  //   portfolio_img: "/images/portfolio_2.png",
  //   portfolio_url: "https://sleepy-plains-55156.herokuapp.com/",
  //   portfolio_color: "portfoli__tag--color3",
  // },
  // {
  //   portfolio_name: "Unityのカーレース",
  //   portfolio_date: "2023.3.10",
  //   portfolio_tag: "Unity",
  //   portfolio_img: "/images/portfolio_2.png",
  //   portfolio_url: "",
  //   portfolio_color: "portfoli__tag--color3",
  // },
];

export const skills = [
  {
    name: "HTML",
    rank: "★★★★",
    tag: "経験年数：3年",
    icon: faHtml5,
  },
  {
    name: "CSS(SCSS)",
    rank: "★★★★",
    tag: "経験年数：3年",
    icon: faCss3,
  },
  {
    name: "JavaScript,TypeScript(jQuery)",
    rank: "★★★",
    tag: "経験年数：2年",
    icon: faJs,
  },
  {
    name: "Ruby on Rails",
    rank: "★★",
    tag: "経験年数：1年",
    icon: faGem,
  },
  {
    name: "React/Next.js",
    rank: "★★★",
    tag: "経験年数：1年",
    icon: faReact,
  },
  {
    name: "Vue.js/Nuxt.js",
    rank: "★",
    tag: "経験年数：1ヶ月",
    icon: faVuejs,
  },
  {
    name: "Unity",
    rank: "★★",
    tag: "経験年数：3ヶ月",
    icon: faUnity,
  },
  // {
  //   name: "Golang",
  //   rank: "★★",
  //   tag: "経験年数：3ヶ月",
  //   icon: faGolang,
  // },
  {
    name: "WordPress",
    rank: "★★★",
    tag: "経験年数：1年",
    icon: faWordpress,
  },
  {
    name: "PhotoShop/Illustrator",
    rank: "★★★",
    tag: "経験年数：1年半",
    icon: faCamera,
  },
];

export const timelines = [
  {
    title: "市立札幌大通高等学校　卒業",
    date: "2020年3月",
    body: "",
  },
  {
    title: "北星学園大学　経済学部　経営情報学科　入学",
    date: "2020年4月",
    body: "",
  },
  {
    title: "JBA日本ビジネスアート株式会社　長期インターン",
    date: "2020年3月",
    body: "Wordpressサイトの修正やhtml,cssのコーディングやPhotoshopなどのWebデザインの制作を半年間行う",
  },
  {
    title: "株式会社conexio　長期インターン",
    date: "2022年4月",
    body: "Ruby on Railsの自社サービスアプリの開発を行う。2022年12月まで行った",
  },
  {
    title: "株式会社メディアライツ　長期インターン",
    date: "2022年9月",
    body: "Unityなどを用いたスマホゲーム開発を行っている",
  },
  {
    title: "株式会社Poteto　長期インターン",
    date: "2023年2月",
    body: "Reactのサービスの開発を行う。バックエンドがPython,インフラがAWSなど使った事がない技術が多くあり、勉強になっている。",
  },
];
