#!/usr/bin/env sh

echo "----- start pre-commit -------"

# コードフォーマット
yarn oxfmt --write .

# リンター（OxLint）
yarn lint

# スタイルリンター（Stylelint）
yarn lint:stylelint

# ビルド（型チェックも含む）
yarn build

# Storybookビルド
yarn build-storybook

# テスト（Node環境）
yarn test --project node

echo "----- end pre-commit -------"